import { ImageProvider } from '@hiarc-platform/ui';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { NextImageAdapter } from './shared/provider/next-image-adapter';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Admin App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ImageProvider imageComponent={NextImageAdapter}>
        <body className={inter.className}>{children}</body>
      </ImageProvider>
    </html>
  );
}
