import { NextImageAdapter } from '@/shared/provider/next-image-adapter';
import Footer from '@/ui/Footer';
import Header from '@/ui/Header';
import { ImageProvider } from '@hiarc-platform/ui';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Intra App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.ReactElement {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ImageProvider imageComponent={NextImageAdapter}>
          <Header />
          {children}
          <Footer />
        </ImageProvider>
      </body>
    </html>
  );
}
