const FontStyle = {
  display2Heavy:
    'font-size: 12rem; letter-spacing: 10px; line-height: 12rem; font-weight: 700; font-family: "NanumSquareNeoHeavy";',
  display1Heavy: 'font-size: 2.8rem; font-weight: 700; font-family: "NanumSquareNeoHeavy";',
  display1ExtraBold: 'font-size: 2.8rem; font-weight: 700; font-family: "NanumSquareNeoExtraBold";',
  display3Bold: 'font-size: 3.2rem; font-weight: 700; font-family: "NanumSquareNeo";',
  display3SemiBold: 'font-size: 3.2rem; font-weight: 600; font-family: "NanumSquareNeo";',
  display2Bold: 'font-size: 2.8rem; font-weight: 700; font-family: "NanumSquareNeo";',
  display2SemiBold: 'font-size: 2.8rem; font-weight: 600; font-family: "NanumSquareNeo";',
  display1Bold: 'font-size: 2.4rem; font-weight: 700; font-family: "NanumSquareNeo";',
  display1SemiBold: 'font-size: 2.4rem; font-weight: 600; font-family: "NanumSquareNeo";',
  headlineBold: 'font-size: 2.0rem; font-weight: 700; font-family: "NanumSquareNeo";',
  headlineSemiBold: 'font-size: 2.0rem; font-weight: 600; font-family: "NanumSquareNeo";',
  subhead3Bold: 'font-size: 1.6rem; font-weight: 700; font-family: "NanumSquareNeo";',
  subhead3ExtraBold: 'font-size: 1.6rem; font-weight: 800; font-family: "NanumSquareNeoExtraBold";',
  subhead3SemiBold: 'font-size: 1.6rem; font-weight: 600; font-family: "NanumSquareNeo";',
  subhead2Bold: 'font-size: 1.4rem; font-weight: 700; font-family: "NanumSquareNeo";',
  subhead2SemiBold: 'font-size: 1.4rem; font-weight: 600; font-family: "NanumSquareNeo";',
  subhead1Bold: 'font-size: 1.2rem; font-weight: 700; font-family: "NanumSquareNeo";',
  subhead1SemiBold: 'font-size: 1.2rem; font-weight: 600; font-family: "NanumSquareNeo";',
  subhead1ExtraBold: 'font-size: 1.2rem; font-weight: 800; font-family: "NanumSquareNeoExtraBold";',
  body3Medium: 'font-size: 1.8rem; font-weight: 500; font-family: "NanumSquareNeo";',
  body3Regular: 'font-size: 1.8rem; font-weight: 400; font-family: "NanumSquareNeo";',
  body2Medium: 'font-size: 1.6rem; font-weight: 500; font-family: "NanumSquareNeo";',
  body2Regular: 'font-size: 1.6rem; font-weight: 400; font-family: "NanumSquareNeo";',
  body1Medium: 'font-size: 1.4rem; font-weight: 500; font-family: "NanumSquareNeo";',
  body1Regular: 'font-size: 1.4rem; font-weight: 400; font-family: "NanumSquareNeo";',
  captionMedium: 'font-size: 1.2rem; font-weight: 500; font-family: "NanumSquareNeo";',
  captionRegular: 'font-size: 1.2rem; font-weight: 400; font-family: "NanumSquareNeo";',
  descriptionMedium: 'font-size: 1rem; font-weight: 500; font-family: "NanumSquareNeo";',
  descriptionRegular: 'font-size: 1rem; font-weight: 400; font-family: "NanumSquareNeo";',
};

export default FontStyle;
