export const NumberToTear = (tier: number) => {
  if (tier == 0) return 'UnRank';
  if (tier == 1) return 'Bronze 5';
  if (tier == 2) return 'Bronze 4';
  if (tier == 3) return 'Bronze 3';
  if (tier == 4) return 'Bronze 2';
  if (tier == 5) return 'Bronze 1';
  if (tier == 6) return 'Silver 5';
  if (tier == 7) return 'Silver 4';
  if (tier == 8) return 'Silver 3';
  if (tier == 9) return 'Silver 2';
  if (tier == 10) return 'Silver 1';
  if (tier == 11) return 'Gold 5';
  if (tier == 12) return 'Gold 4';
  if (tier == 13) return 'Gold 3';
  if (tier == 14) return 'Gold 2';
  if (tier == 15) return 'Gold 1';
  if (tier == 16) return 'Platinum 5';
  if (tier == 17) return 'Platinum 4';
  if (tier == 18) return 'Platinum 3';
  if (tier == 19) return 'Platinum 2';
  if (tier == 20) return 'Platinum 1';
  if (tier == 21) return 'Diamond 5';
  if (tier == 22) return 'Diamond 4';
  if (tier == 23) return 'Diamond 3';
  if (tier == 24) return 'Diamond 2';
  if (tier == 25) return 'Diamond 1';
  if (tier == 26) return 'Ruby 5';
  if (tier == 27) return 'Ruby 4';
  if (tier == 28) return 'Ruby 3';
  if (tier == 29) return 'Ruby 2';
  if (tier == 30) return 'Ruby 1';
  if (tier == 31) return '홍대 1짱';
};
