const CellType = {
  CIRCLE: "CIRCLE",
  CIRCLE_WITH_TEXT: "CIRCLE_WITH_TEXT",
  CIRCLE_WITH_ICON: "CIRCLE_WITH_ICON",
  BUTTON: "BUTTON",
  BUTTON_WITH_ICON: "BUTTON_WITH_ICON",
  LONG_BUTTON_WITH_ICON: "LONG_BUTTON_WITH_ICON",
  HORIZONTAL_RECTANGLE: "HORIZONTAL_RECTANGLE",
  BORDERED_HORIZONTAL_RECTANGLE: "BORDERED_HORIZONTAL_RECTANGLE",
  LONG_HORIZONTAL_RECTANGLE: "LONG_HORIZONTAL_RECTANGLE",
  BORDERED_LONG_HORIZONTAL_RECTANGLE: "BORDERED_LONG_HORIZONTAL_RECTANGLE",
  VERTICAL_RECTANGLE: "VERTICAL_RECTANGLE",
  TEXT: "TEXT",
  CURVE: "CURVE",
  ANIMATE_CURVE: "ANIMATE_CURVE",
  ANIMATE_CURVE_WITH_DELAY: "ANIMATE_CURVE_WITH_DELAY",
  IMAGE: "IMAGE",
  ICON: "ICON",
};

export default CellType;
